variables:
    ANSIBLE_FORCE_COLOR: 'true'

stages:
  - test
  - build-and-deploy

.run_on_dockerhost: &run_on_dockerhost
  tags:
    - docker20
  before_script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
  image: gitlab.aimms.com:5050/other/dockerdev/documentation:latest

linkcheck:
  <<: *run_on_dockerhost
  stage: test
  variables:
    SPHINX_IGNORE_EXTERNAL_LINKS: "true"
  script:
    - python3 -msphinx -W --keep-going -b linkcheck . _build/linkcheck

linkcheck_external:
  <<: *run_on_dockerhost
  stage: test
  script:
    - python3 -msphinx -W --keep-going -b linkcheck . _build/linkcheck
  allow_failure: true

spellcheck:
  <<: *run_on_dockerhost
  stage: test
  script:
    - python3 --version
    - pip freeze
    - python3 -msphinx -W --keep-going -b spelling . _build/spelling

build:
  <<: *run_on_dockerhost
  stage: test
  script:
    - sphinx-build -W --keep-going -b html . _build/html

  artifacts:
    paths:
      - _build/html/**/*

deploy:
  <<: *run_on_dockerhost
  stage: build-and-deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      when: on_success
    - when: never
  script:
    - sphinx-build -b html . _build/html
    - bash load_ssh_key_for_deploy.sh
    - rsync -rt _build/html/ support@data.aimms.com:/home/aimms/www/documentation.aimms.com
  retry: 1

az_deploy:
  <<: *run_on_dockerhost
  stage: build-and-deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      when: on_success
    - when: never
  script:
    - sphinx-build -b html . _build/html
    - az storage copy -s '_build/html' --recursive --destination-container '$web' -- --overwrite=true --as-subdir=false
