variables:
    ANSIBLE_FORCE_COLOR: 'true'

stages:
  - test
  - build-and-deploy

before_script:
  - sudo apt-get install software-properties-common -y
  - sudo add-apt-repository ppa:deadsnakes/ppa -y
  - sudo apt-get update -y
  - sudo apt-get install python3.10.1 python3.10.1-dev python3.10.1-venv python3-pip python3-venv python-enchant -y
  - python3.10 -mvenv ../myenv
  - source ../myenv/bin/activate
  - python3.10 -mpip install --upgrade  pip
  - python3.10 -mpip install -U sphinx sphinx-sitemap sphinx-last-updated-by-git sphinxcontrib-bibtex sphinxcontrib-spelling
  - python3.10 -mpip install -U --force-reinstall sphinx-aimms-theme

linkcheck:
  stage: test
  script:
  - python3 -msphinx -W --keep-going -b linkcheck . _build/linkcheck
  allow_failure: true
  tags: 
    - ubuntu
  retry: 1

spellcheck:
  stage: test
  script:
  - python3 --version
  - pip freeze
  - python3 -msphinx -W --keep-going -b spelling . _build/spelling
  allow_failure: true
  tags: 
    - ubuntu

build:
  stage: test
  script:
    - sphinx-build -W --keep-going -b html . _build/html 
  tags: 
    - ubuntu

deploy:
  stage: build-and-deploy
  script:
    - sphinx-build -b html . _build/html
    - rsync -rt _build/html/ support@data.aimms.com:/home/aimms/www/documentation.aimms.com
  tags: 
    - ubuntu
  only:
    - master
  retry: 1
